name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ '**' ]

jobs:
    build-backend:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: 11
            -   name: Build with Maven
                run: mvn --show-version --batch-mode verify --file pom.xml

    build-frontend:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 10.x, 12.x, 14.x, 15.x ]
        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -   run: npm --prefix penda ci
            -   run: npm --prefix penda run build
            -   run: npm --prefix penda run lint
            -   run: npm --prefix penda run test -- --watch=false
            -   name: Run e2e tests
                run: |
                    cd penda
                    npx webdriver-manager -- update --versions.chrome="$(google-chrome --version | cut -d ' ' -f 3)"
                    npm run fake-server &
                    npx ng e2e
